on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: LFTP rsync check     #synchronizace na FTP skrze LFTP klient (volitelné)
      run:  |
        sudo apt-get install -y lftp
        lftp -u "${{ secrets.ftp_username }}","${{ secrets.ftp_password }}" ftp://${{ secrets.ftp_server }} <<EOF
        set ssl:verify-certificate no
        mirror -R --only-newer --parallel=10 --exclude .git --exclude .github --exclude README.md ./ deploy.martin-kudela.cz
        bye
        EOF
